#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define bMUGSHOT_SIDNEY      0
#define bMUGSHOT_PHOEBE      1
#define bMUGSHOT_GLACIA      2
#define bMUGSHOT_DRAKE       3
#define bMUGSHOT_CHAMPION    4
#define bMUGSHOT_MAY         5
#define bMUGSHOT_BRENDAN     6

#define MUGSHOTS_COUNT      7

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H
