#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

//Add your mugshot constants here
#define MUGSHOT_MANGROVE 0
#define MUGSHOT_MAY 1
#define MUGSHOT_BRENDAN 2
#define MUGSHOT_SIDNEY 3
#define MUGSHOT_WAYNE 4
#define MUGSHOT_SUDOWOODO 5
#define MUGSHOT_TANDEMAUS 6
#define MUGSHOT_BURROWL 7

#endif