gText_Birch_Welcome::
	.string "Howdy!\n"
	.string "Welcome to the world of FLORIDA!\p"
	.string "They call me Mike Mangrove.\p"
	.string "But actually, I just got my Ph.D.\p"
    .string "So, call me...\p"
    .string "Professor Mangrove, haha. \p"
	.string "$"

gText_Birch_Pokemon::
	.string "By the way, check this out.\p"

	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "I'm telling you, man,\n"
	.string "POKéMON are huge in Florida.\p"
	.string "Sometimes they're dangerous...\p"
	.string "You don't need a permit to own one.\p"
	.string "But honestly? Most of the time,\n"
	.string "POKéMON are like family.\l"
	.string "But even at the University of Florida,\p"
	.string "there's some things that we just\n"
	.string "don't know about the POKéMON here. \p"
	.string "Now that I'm a PROFESSOR,\l"
	.string "I can start my passion project,\p"
	.string "discovering the link between POKéMON\n"
	.string "and the FLORIDA climate.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Oh yeah, by the way...\p"
    .string "$"

gText_Birch_BoyOrGirl::
    .string "Did you bring your bathing suit?\p"
    .string "$"

gText_Birch_WhatsYourName::
    .string "Good deal, buddy.\n"
	.string "Anyway, what's your name?$"

gText_Birch_SoItsPlayer::
	.string "My bad, one more time: {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "For sure, for sure.\p"
	.string "Glad to know ya, {PLAYER}{KUN}.\n"
	.string "So, you're moving to Wellington?\l"
	.string "That's my hometown, man!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Alright, you ready for this?\p"
	.string "This is YOUR story, it's up to you\n"
	.string "to make big things happen, okay?\p"
	.string "Stick around and check out FLORIDA,\n"
	.string "just make sure you wear sunscreen,\l"
	.string "and seriously: be good to POKéMON.\p"
	.string "Don't be a stranger, alright?\n"
	.string "Hit me up later in my POKéMON LAB.\p"
	.string "$"
