gText_Birch_Welcome::
	.string "Howdy!\p"
	.string "Welcome to the world of Florida!\p"
	.string "It's your boy, Mike Mangrove.\p"
	.string "Well, since I just finished my Ph.D.\n"
    .string "I guess it's Professor Mangrove now!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "By the way, check this out.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Florida rocks because you can find\n"
	.string "Pokémon pretty much anywhere you look.\p"
	.string "Pokémon are our wildlife, our coworkers,\n"
	.string "our self-defense, and our family,\l"
    .string "so we treat them with respect.\p"
    .string "I studied Pokémon at the University of\n"
	.string "Florida, but we don't know everything.\p"
	.string "Right now, I'm studying the link between\n"
	.string "Pokémon and the Florida climate.\p"
    .string "Why is Florida getting hotter every year?\n"
	.string "Why are hurricanes growing stronger?\p"
	.string "Florida has always been a weird place,\n"
	.string "but something weird is going on, man.\l"
	.string "My job is to figure out what it is.\p"
	.string "$"    

gText_Birch_AndYouAre::
	.string "Oh yeah, by the way...$"

gText_Birch_BoyOrGirl::
    .string "This is really important:\n"
    .string "Did you bring a bathing suit?$"

gText_Birch_WhatsYourName::
    .string "Good deal, buddy.\n"
	.string "Anyway, what's your name?$"

gText_Birch_SoItsPlayer::
	.string "My bad, one more time: {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "For sure, for sure.\p"
	.string "What's up, {PLAYER}{KUN}?\n"
	.string "So, you're moving to Wellington?\l"
	.string "That's my hometown, man!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Alright, you ready for this?\p"
	.string "This is YOUR story, it's up to you\n"
	.string "to make big things happen, okay?\p"
	.string "Stick around and check out Florida,\n"
	.string "just make sure you wear sunscreen,\l"
	.string "and seriously: be good to Pokémon.\p"
	.string "Don't be a stranger, alright?\n"
	.string "Hit me up later in my Pokémon lab.\p"
	.string "$"
